/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "ejev3.h"

bool_t
xdr_tuple (XDR *xdrs, tuple *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->key))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->value1, 256))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->value2))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->value3))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_t_tuple (XDR *xdrs, t_tuple *objp)
{
	register int32_t *buf;

	 if (!xdr_tuple (xdrs, objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_service (XDR *xdrs, service *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->status))
		 return FALSE;
	 if (!xdr_t_tuple (xdrs, &objp->content))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_t_service (XDR *xdrs, t_service *objp)
{
	register int32_t *buf;

	 if (!xdr_service (xdrs, objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_set_value_tuples_1_argument (XDR *xdrs, set_value_tuples_1_argument *objp)
{
	 if (!xdr_int (xdrs, &objp->key))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->value1, 256))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->value2))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->value3))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_modify_value_tuples_1_argument (XDR *xdrs, modify_value_tuples_1_argument *objp)
{
	 if (!xdr_int (xdrs, &objp->key))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->value1, 256))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->value2))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->value3))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_copy_key_tuples_1_argument (XDR *xdrs, copy_key_tuples_1_argument *objp)
{
	 if (!xdr_int (xdrs, &objp->key1))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->key2))
		 return FALSE;
	return TRUE;
}
